version: '3.7'
services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env

  frontend:
    image: h0diush/foodgram_frontend
    volumes:
      - frontend_data:/app/build/
    depends_on:
      - db

  web:
    image: h0diush/foodgram_backend
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_data:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/code/backend_static/
      - media_value:/code/media/
    depends_on:
      - web
      - frontend

volumes:
  postgres_data:
  frontend_data:
  static_value:
  media_value: