# Generated by Django 3.0.5 on 2021-08-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты'},
        ),
    ]
