# Generated by Django 3.0.5 on 2021-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.IngredientRecord', to='recipe.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
