# Generated by Django 3.0.5 on 2021-09-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210902_2045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientrecord',
            name='unique_ingredient',
        ),
    ]
