# Generated by Django 3.0.5 on 2021-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210902_2124'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientrecord',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient'),
        ),
    ]
