# Generated by Django 3.0.5 on 2021-08-31 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210831_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecord',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecord', to='recipe.Ingredients'),
        ),
    ]
