# Generated by Django 3.0.5 on 2021-08-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210806_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='qty',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='units',
            new_name='measurement_unit',
        ),
    ]
