# Generated by Django 3.0.5 on 2021-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210809_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время приготовления в минутах'),
        ),
    ]
