# Generated by Django 3.0.5 on 2021-08-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0010_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_shops_list', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
