# Generated by Django 3.0.5 on 2021-08-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20210815_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='shop_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='shops_list', to='recipe.Recipe', verbose_name='Рецепты'),
        ),
    ]
