# Generated by Django 3.0.5 on 2021-08-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorit_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to='recipe.Recipe', verbose_name='Избранный рецепты'),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='shop_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_list', to='recipe.Recipe', verbose_name='Рецепты'),
        ),
    ]
