# Generated by Django 3.0.5 on 2021-08-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20210816_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorit_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoplist',
            old_name='shop_list',
            new_name='recipe',
        ),
    ]
